name: Docker CI/CD pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image
        run: |
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }} .
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker stop webapp || true
            sudo docker rm webapp || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}//webapp:${{ github.sha }}
            sudo docker run -d --name webapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}//webapp:${{ github.sha }}
